# Generated by Django 4.2.17 on 2025-03-07 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='newsletter',
            field=models.BooleanField(default=False),
        ),
    ]
