# Generated by Django 4.2.18 on 2025-01-24 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets_review', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='day_time',
            field=models.CharField(default='unknown'),
        ),
        migrations.AddField(
            model_name='market',
            name='location',
            field=models.CharField(default='unknown'),
        ),
    ]
