# Generated by Django 4.2.18 on 2025-01-25 01:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('markets_review', '0002_market_day_time_market_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='market',
            options={'ordering': ['-created_on']},
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=400)),
                ('stars_rating', models.IntegerField(choices=[(0, '5 *'), (1, '4 *'), (2, '3 *'), (3, '2 *'), (4, '1 *'), (5, '0 *')], default=0)),
                ('visit_again', models.IntegerField(choices=[(0, 'Yes'), (1, 'No')], default=0)),
                ('approved', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_author', to=settings.AUTH_USER_MODEL)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_reviews', to='markets_review.market')),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
    ]
