# Generated by Django 4.2.18 on 2025-01-25 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets_review', '0003_alter_market_options_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='created_on',
            field=models.DateField(auto_now_add=True),
        ),
    ]
