# Generated by Django 4.2.18 on 2025-01-25 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('markets_review', '0004_alter_review_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='stars_rating',
            field=models.IntegerField(choices=[(0, '0 *'), (1, '1 *'), (2, '2 *'), (3, '3 *'), (4, '4 *'), (5, '5 *')], default=5),
        ),
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.IntegerField()),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_ratings', to='markets_review.market')),
            ],
        ),
    ]
