# Generated by Django 4.2.17 on 2025-02-07 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('markets_review', '0007_alter_review_author_alter_review_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='name',
            new_name='market',
        ),
    ]
