# Generated by Django 4.2.17 on 2025-02-07 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('markets_review', '0008_rename_name_review_market'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ratings',
            old_name='name',
            new_name='market',
        ),
    ]
