# Generated by Django 4.2.17 on 2025-02-11 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets_review', '0009_rename_name_ratings_market'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='visit_again',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True),
        ),
    ]
