# Generated by Django 4.2.17 on 2025-02-18 22:25

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('markets_review', '0010_alter_review_visit_again'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='stars_rating',
            field=models.IntegerField(choices=[(5, '5 *'), (4, '4 *'), (3, '3 *'), (2, '2 *'), (1, '1 *'), (0, '0 *')], default=5),
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picture', to='markets_review.market')),
            ],
        ),
    ]
