# Generated by Django 4.2.17 on 2025-02-22 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('markets_review', '0011_alter_review_stars_rating_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='market',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_pictures', to='markets_review.market'),
        ),
    ]
