# Generated by Django 4.2.17 on 2025-02-25 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('markets_review', '0012_alter_picture_market'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='market',
            name='review_rating',
        ),
    ]
